// Command genoui builds the OUI vendor table from the public IEEE registries.
//
// The IEEE publishes the MAC address block assignments as CSV. They are the
// authoritative source for "which company made this hardware", and they are the
// single cheapest improvement available to passive identification: a MAC address
// is present in every DHCP and ARP record, and without this table it resolves to
// nothing at all.
//
// Three registries are merged, in increasing order of prefix length:
//
//	MA-L  24-bit  (6 hex)  the classic OUI, one block per large vendor
//	MA-M  28-bit  (7 hex)  medium blocks, shared under one MA-L
//	MA-S  36-bit  (9 hex)  small blocks, for vendors buying a fraction of a block
//
// Longest prefix wins at lookup time, so a device from a small vendor holding an
// MA-S block resolves to that vendor rather than to the registrar that owns the
// enclosing MA-L.
//
// Run with -fetch to download the registries, or point it at local copies:
//
//	go run ./tools/genoui -fetch -out internal/identify/data/oui.tsv
//
// The output is deliberately plain TSV rather than generated Go. It is data, it
// changes on IEEE's schedule rather than ours, and keeping it as data means it
// can move to the fingerprint repository later without touching any code.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// The three public IEEE registry downloads.
var sources = []struct {
	name string
	url  string
}{
	{"MA-L", "https://standards-oui.ieee.org/oui/oui.csv"},
	{"MA-M", "https://standards-oui.ieee.org/oui28/mam.csv"},
	{"MA-S", "https://standards-oui.ieee.org/oui36/oui36.csv"},
}

func main() {
	fetch := flag.Bool("fetch", false, "download the registries from IEEE instead of reading local files")
	dir := flag.String("dir", ".", "directory holding oui.csv, mam.csv and oui36.csv when not fetching")
	out := flag.String("out", "internal/identify/data/oui.tsv", "output file")
	flag.Parse()

	entries := map[string]string{}
	for i, src := range sources {
		var r io.Reader
		if *fetch {
			fmt.Fprintf(os.Stderr, "fetching %s ...\n", src.url)
			body, err := download(src.url)
			if err != nil {
				fatal("fetch %s: %v", src.name, err)
			}
			defer body.Close()
			r = body
		} else {
			local := []string{"oui.csv", "mam.csv", "oui36.csv"}[i]
			f, err := os.Open(filepath.Join(*dir, local))
			if err != nil {
				fatal("open %s: %v", local, err)
			}
			defer f.Close()
			r = f
		}
		n, err := parse(r, entries)
		if err != nil {
			fatal("parse %s: %v", src.name, err)
		}
		fmt.Fprintf(os.Stderr, "%s: %d assignments\n", src.name, n)
	}

	prefixes := make([]string, 0, len(entries))
	for p := range entries {
		prefixes = append(prefixes, p)
	}
	// Sort by prefix so the file diffs cleanly when IEEE adds assignments.
	sort.Strings(prefixes)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatal("mkdir: %v", err)
	}
	f, err := os.Create(*out)
	if err != nil {
		fatal("create %s: %v", *out, err)
	}
	defer f.Close()

	fmt.Fprintf(f, "# MAC address prefix -> vendor, generated by tools/genoui. Do not edit by hand.\n")
	fmt.Fprintf(f, "# Source: the public IEEE MA-L, MA-M and MA-S registry downloads.\n")
	fmt.Fprintf(f, "# Regenerate with: go run ./tools/genoui -fetch\n")
	fmt.Fprintf(f, "# %d assignments, retrieved %s.\n", len(prefixes), time.Now().UTC().Format("2006-01-02"))
	for _, p := range prefixes {
		fmt.Fprintf(f, "%s\t%s\n", p, entries[p])
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d prefixes)\n", *out, len(prefixes))
}

func download(url string) (io.ReadCloser, error) {
	req, _ := http.NewRequest("GET", url, nil)
	// IEEE rejects requests without a User-Agent.
	req.Header.Set("User-Agent", "tarsier-genoui/1.0 (+https://github.com/kapoordeepanshu/tarsier)")
	resp, err := (&http.Client{Timeout: 5 * time.Minute}).Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("http %s", resp.Status)
	}
	return resp.Body, nil
}

// parse reads one IEEE registry CSV into the prefix table.
func parse(r io.Reader, into map[string]string) (int, error) {
	cr := csv.NewReader(r)
	cr.FieldsPerRecord = -1 // IEEE rows occasionally carry a stray trailing field
	cr.LazyQuotes = true    // and occasionally an unescaped quote in an address

	n := 0
	for {
		rec, err := cr.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			// A malformed address field must not cost us the whole registry.
			continue
		}
		if len(rec) < 3 || rec[0] == "Registry" {
			continue
		}
		prefix := strings.ToUpper(strings.TrimSpace(rec[1]))
		vendor := cleanVendor(rec[2])
		if prefix == "" || vendor == "" {
			continue
		}
		// Blocks IEEE has assigned to itself as registrar carry no useful
		// vendor: they mean "this MA-L is subdivided", and the real owner is in
		// the MA-M or MA-S table under a longer prefix.
		if strings.Contains(strings.ToLower(vendor), "ieee registration authority") {
			continue
		}
		into[prefix] = vendor
		n++
	}
	return n, nil
}

// corporate suffixes stripped from the end of an organisation name, longest
// first so "Co., Ltd." is removed before "Ltd".
var suffixes = []string{
	"co., ltd.", "co.,ltd.", "co., ltd", "co.,ltd", "co ltd", "co., limited",
	"company limited", "company, ltd.", "corporation", "incorporated",
	"limited", "gmbh & co. kg", "gmbh", "co., inc.", "co.,inc.",
	"inc.", "inc", "llc.", "llc", "ltd.", "ltd", "l.t.d.",
	"corp.", "corp", "s.a.", "s.a", "b.v.", "bv", "n.v.", "nv",
	"a/s", "aps", "ab", "oy", "as", "sas", "sarl", "s.r.l.", "srl",
	"spa", "s.p.a.", "plc", "pty", "pte", "pvt", "co.", "company",
	"technology co", "technologies co",
}

// cleanVendor turns an IEEE organisation name into something worth showing a
// user. "Cisco Systems, Inc" and "Nokia Shanghai Bell Co., Ltd." are the same
// fact as "Cisco Systems" and "Nokia Shanghai Bell", and the shorter form is
// what fits in a device table.
func cleanVendor(s string) string {
	s = strings.TrimSpace(s)
	// Collapse internal whitespace, including the newlines some rows contain.
	s = strings.Join(strings.Fields(s), " ")
	if s == "" || strings.EqualFold(s, "private") {
		return ""
	}

	// Strip corporate suffixes repeatedly: "Foo Technology Co., Ltd." sheds
	// "Ltd." then "Co." then stops.
	for changed := true; changed; {
		changed = false
		lower := strings.ToLower(s)
		for _, suf := range suffixes {
			if !strings.HasSuffix(lower, " "+suf) && !strings.HasSuffix(lower, ","+suf) {
				continue
			}
			s = strings.TrimSpace(s[:len(s)-len(suf)])
			s = strings.TrimRight(s, " ,.-")
			changed = true
			break
		}
	}

	s = strings.TrimRight(s, " ,.-")
	// A name that shed everything meaningful is worse than no name.
	if len(s) < 2 {
		return ""
	}
	// TSV is the storage format, so a literal tab would corrupt the file.
	return strings.ReplaceAll(s, "\t", " ")
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genoui: "+format+"\n", args...)
	os.Exit(1)
}
